name: Run checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: install nox
        run: |
          python -m pip install nox
      - name: lint
        run: |
          python -m nox -s lint
  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install nox
        run: |
          python -m pip install nox
      - name: Run pyright
        run: |
          python -m nox -s type-check

      - name: Show fail comments
        if: always()
        uses: jakebailey/pyright-action@v1.0.3
        with:
          warnings: true
  verify-types:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install nox
        run: |
          python -m pip install nox
      - name: Run type checker
        run: |
          python -m nox -s verify-types
